# Generated by Django 4.0.1 on 2022-02-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="train",
            old_name="travel_table",
            new_name="travel_time",
        ),
    ]
