# Generated by Django 4.0.1 on 2022-02-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trains", "0002_rename_travel_table_train_travel_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="train",
            options={
                "ordering": ["travel_time"],
                "verbose_name": "Поезд",
                "verbose_name_plural": "Поезда",
            },
        ),
    ]
