# Generated by Django 4.0.1 on 2022-02-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="travel_times",
            new_name="total_time",
        ),
    ]
