# Generated by Django 4.0.1 on 2022-02-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_rename_travel_times_route_total_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="total_time",
            new_name="travel_times",
        ),
    ]
